### ISSUE TITLE
Methos getHost  return "undefined"

### ISSUE THREAD

**Issue by alexndlm** [matteosister/CypressAngularNgRoutingBundle#1]
If hosttokens not seted method getHost must return cypress.NgRouter.host as default value

**Comment by matteosister** [comment]
:+1: Many thanks! here it is: https://github.com/matteosister/CypressAngularNgRoutingBundle/commit/d81255f4d481f6e4b2ebf7e178ea16b47eb9dd93

released as version 0.1.1

**Comment by alexndlm** [comment]
Great )
